"""Add quiz_name column to Quiz model

Revision ID: bf0ba616938a
Revises: 3b35dbcee661
Create Date: 2025-03-25 23:42:03.871136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0ba616938a'
down_revision = '3b35dbcee661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('quiz_name')

    # ### end Alembic commands ###
